# Generated by Django 4.2.16 on 2024-09-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
